import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import ReduxProvider from '@/components/ReduxProvider'; // ✅ Client wrapper


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {/* Alert Banner */}
          <div className="bg-saffron text-white py-2 px-4 text-center">
            <p className="text-sm">
              🍽️ “Freshly Prepared. Google-Certified Chefs. Real Home Food — Made Just for You.”
            </p>
          </div>
          <Navigation />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
