import { MessageSquare, ChefHat } from "lucide-react";

export const menuItems = [
  {
    id: "47c53ef1",
    name: "Aloo Paratha with Raita",
    description: "Made with Desi Ghee + Freshly Mint Curd",
    price: 165,
    category: "chefs-special",
    image: "https://source.unsplash.com/400x300/?aloo-paratha",
    rating: 4.8,
    veg: true,
    popular: true,
    preparationTime: "35 mins",
  },
  {
    id: "32e206a1",
    name: "Batata Kandha Poha",
    description: "Made with potato and onion and coriander leaves",
    price: 120,
    category: "chefs-special",
    image:
      "https://images.unsplash.com/photo-1604908178063-325f9e085cc9?w=400&h=300&fit=crop",
    rating: 4.9,
    veg: true,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "46e83da6",
    name: "Pav Bhaji",
    description:
      "2 bhaji pav in butter + mashed veg made in fresh tomato puree",
    price: 175,
    category: "chefs-special",
    image:
      "https://images.unsplash.com/photo-1604908178063-325f9e085cc9?w=400&h=300&fit=crop",
    rating: 4.5,
    veg: true,
    popular: false,
    preparationTime: "25 mins",
  },
  {
    id: "1122f00f",
    name: "Paneer Lajawab Roll (Also in Rocking Rolls)",
    description:
      "Roll made with fresh juicy paneer, red bell pepper, onion and a variety of sauces",
    price: 195,
    category: "chefs-special",
    image:
      "https://images.unsplash.com/photo-1604908178063-325f9e085cc9?w=400&h=300&fit=crop",
    rating: 4.4,
    veg: true,
    popular: false,
    preparationTime: "20 mins",
  },
  {
    id: "95d583c6",
    name: "Veg Hakka Noodles with Veg Manchurian Gravy",
    description: "Made with homemade herbs. No MSG",
    price: 255,
    category: "combos",
    image:
      "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&h=300&fit=crop",
    rating: 4.7,
    veg: true,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "4d63851e",
    name: "Non-Veg Hakka Noodles with Non-Veg Manchurian Gravy",
    description: "Delicious item prepared freshly",
    price: 345,
    category: "combos",
    image:
      "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&h=300&fit=crop",
    rating: 4.8,
    veg: false,
    popular: true,
    preparationTime: "35 mins",
  },
  {
    id: "bd2b1667",
    name: "Schezwan Fried Rice with Veg Manchurian Gravy",
    description: "Long grain rice with fresh bell peppers",
    price: 255,
    category: "combos",
    image:
      "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&h=300&fit=crop",
    rating: 4.7,
    veg: true,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "bf2b6a19",
    name: "Schezwan Fried Rice with Non-Veg Manchurian Gravy",
    description: "Delicious item prepared freshly",
    price: 345,
    category: "combos",
    image:
      "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&h=300&fit=crop",
    rating: 4.4,
    veg: false,
    popular: false,
    preparationTime: "15 mins",
  },
  {
    id: "82503880",
    name: "Lauki Kofta with 2 Parathas",
    description: "Four creamy kofta balls in tomato gravy with fresh cream",
    price: 250,
    category: "combos",
    image:
      "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&h=300&fit=crop",
    rating: 4.7,
    veg: true,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "8213b863",
    name: "Paneer Pasanda Gravy + 2 Parathas",
    description: "Makhani Gravy with chef's special masala",
    price: 295,
    category: "combos",
    image:
      "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&h=300&fit=crop",
    rating: 4.8,
    veg: true,
    popular: false,
    preparationTime: "15 mins",
  },
  {
    id: "bfe44c04",
    name: "Paneer Lajawab Roll",
    description:
      "Roll made with fresh juicy paneer, red bell pepper, onion and a variety of sauces",
    price: 195,
    category: "rocking-rolls",
    image:
      "https://images.unsplash.com/photo-1606755962773-3b2f5c0e30e1?w=400&h=300&fit=crop",
    rating: 4.8,
    veg: true,
    popular: true,
    preparationTime: "25 mins",
  },
  {
    id: "0affba65",
    name: "Chicken Roll",
    description: "Made with boneless chicken in variety of sauces",
    price: 200,
    category: "rocking-rolls",
    image:
      "https://images.unsplash.com/photo-1606755962773-3b2f5c0e30e1?w=400&h=300&fit=crop",
    rating: 4.9,
    veg: false,
    popular: false,
    preparationTime: "30 mins",
  },
  {
    id: "0eaded49",
    name: "Egg Roll",
    description: "Made in Kolkata style",
    price: 165,
    category: "rocking-rolls",
    image:
      "https://images.unsplash.com/photo-1606755962773-3b2f5c0e30e1?w=400&h=300&fit=crop",
    rating: 4.6,
    veg: false,
    popular: false,
    preparationTime: "40 mins",
  },
  {
    id: "c1ab8687",
    name: "Chicken Curry",
    description: "Cooked in onion, tomato and Indian spices",
    price: 250,
    category: "main-course",
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop",
    rating: 4.5,
    veg: false,
    popular: true,
    preparationTime: "15 mins",
  },
  {
    id: "b53e2f19",
    name: "Egg Curry",
    description: "4 boiled eggs in curry of onion, tomato, and curd",
    price: 250,
    category: "main-course",
    image:
      "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=300&fit=crop",
    rating: 4.7,
    veg: false,
    popular: false,
    preparationTime: "20 mins",
  },
  {
    id: "04324ad5",
    name: "Dahi Khichdi with Curd",
    description: "Made with rice, moong dal, dahi and seasonal vegetables",
    price: 200,
    category: "main-course",
    image:
      "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=300&fit=crop",
    rating: 4.6,
    veg: true,
    popular: true,
    preparationTime: "25 mins",
  },
  {
    id: "1d4f9db4",
    name: "Fish Curry (Dal Maach)",
    description:
      "4 big pieces of fish, Bengali-style cooked in curd and spices",
    price: 540,
    category: "main-course",
    image:
      "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=300&fit=crop",
    rating: 4.9,
    veg: false,
    popular: false,
    preparationTime: "20 mins",
  },
  {
    id: "b2db8a8d",
    name: "Veg Hakka Noodles",
    description: "Made with fresh vegetables and herbs. No MSG",
    price: 155,
    category: "chinese",
    image:
      "https://images.unsplash.com/photo-1589308078056-f207d4c06939?w=400&h=300&fit=crop",
    rating: 4.6,
    veg: true,
    popular: false,
    preparationTime: "20 mins",
  },
  {
    id: "914e7291",
    name: "Non-Veg Hakka Noodles",
    description: "Delicious item prepared freshly",
    price: 250,
    category: "chinese",
    image:
      "https://images.unsplash.com/photo-1589308078056-f207d4c06939?w=400&h=300&fit=crop",
    rating: 4.9,
    veg: false,
    popular: true,
    preparationTime: "20 mins",
  },
  {
    id: "9c7ec32f",
    name: "Veg Schezwan Fried Rice",
    description: "Chef's special masala, Long Grain rice, fresh vegetables",
    price: 155,
    category: "chinese",
    image:
      "https://images.unsplash.com/photo-1589308078056-f207d4c06939?w=400&h=300&fit=crop",
    rating: 4.4,
    veg: true,
    popular: true,
    preparationTime: "40 mins",
  },
  {
    id: "2839e182",
    name: "Non-Veg Schezwan Fried Rice",
    description: "Delicious item prepared freshly",
    price: 250,
    category: "chinese",
    image:
      "https://images.unsplash.com/photo-1589308078056-f207d4c06939?w=400&h=300&fit=crop",
    rating: 4.8,
    veg: false,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "53342947",
    name: "Manchurian Gravy (Veg/Non-Veg)",
    description: "Tangy and tasty gravy",
    price: 150,
    category: "chinese",
    image:
      "https://images.unsplash.com/photo-1589308078056-f207d4c06939?w=400&h=300&fit=crop",
    rating: 4.7,
    veg: false,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "7519897c",
    name: "Fish Fry (4 PCS)",
    description: "Indian style fried fish with side vegetables",
    price: 485,
    category: "chinese",
    image:
      "https://images.unsplash.com/photo-1589308078056-f207d4c06939?w=400&h=300&fit=crop",
    rating: 4.7,
    veg: false,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "914a8118",
    name: "Khichdi Chawal / Roti",
    description: "Made in fresh curd with basmati rice / tawa roti",
    price: 140,
    category: "economy-meals",
    image:
      "https://images.unsplash.com/photo-1625225233840-6954560211cc?w=400&h=300&fit=crop",
    rating: 4.8,
    veg: true,
    popular: true,
    preparationTime: "40 mins",
  },
  {
    id: "c3e70d78",
    name: "Chole / Rajma with Chawal / Roti",
    description: "Rajma or chole in special masala with juicy gravy",
    price: 140,
    category: "economy-meals",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
    rating: 4.5,
    veg: true,
    popular: true,
    preparationTime: "25 mins",
  },
  {
    id: "6a14b8c1",
    name: "Dal Makhani with 2 Parathas / Roti",
    description: "Traditional Dal Makhani with parathas or roti",
    price: 140,
    category: "economy-meals",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    rating: 4.4,
    veg: true,
    popular: false,
    preparationTime: "40 mins",
  },
];

export const processSteps = [
  {
    step: 1,
    title: "Browse Menu",
    description:
      "Explore our daily fresh menu with authentic home-style dishes",
    icon: ChefHat,
    color: "bg-saffron",
  },
  {
    step: 2,
    title: "Fill Your Details",
    description: "Add your contact information and delivery preferences",
    icon: MessageSquare,
    color: "bg-saffron-light",
  },
  {
    step: 3,
    title: "Send Order on WhatsApp",
    description: "Complete your order through our convenient WhatsApp system",
    icon: MessageSquare,
    color: "bg-saffron-dark",
  },
];
